from __future__ import annotations
ax.set_title('Drawdown %')
ax.set_xlabel('Time')
ax.set_ylabel('DD %')
dd_img = _png_b64(fig)


# R-multiple histogram
r_img = ''
if not trades.empty and 'r_multiple' in trades.columns and trades['r_multiple'].notna().any():
fig, ax = plt.subplots(figsize=(6, 3))
ax.hist(trades['r_multiple'].dropna(), bins=20)
ax.set_title('R-Multiple Distribution')
ax.set_xlabel('R')
ax.set_ylabel('Count')
r_img = _png_b64(fig)


# Metrics grid
metrics_rows = [
("CAGR", f"{m.cagr*100:.2f}%"),
("Sharpe (daily)", f"{m.sharpe:.2f}"),
("Sortino", f"{m.sortino:.2f}"),
("Max DD", f"{m.max_dd*100:.2f}%"),
("Profit Factor", f"{m.profit_factor:.2f}"),
("Win Rate", f"{m.win_rate*100:.2f}%"),
("Avg Trade", f"{m.avg_trade:.2f}"),
("Exposure", f"{m.exposure_pct*100:.1f}%"),
]


css = """
<style>
body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 24px; }
.grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
.card { padding: 12px; border: 1px solid #e5e7eb; border-radius: 10px; }
h1 { margin: 0 0 8px 0; font-size: 20px; }
h2 { margin: 16px 0 8px 0; font-size: 16px; }
table { border-collapse: collapse; width: 100%; }
th, td { border-bottom: 1px solid #eee; padding: 6px 8px; text-align: left; }
img { max-width: 100%; height: auto; }
.footer { color: #6b7280; font-size: 12px; margin-top: 16px; }
</style>
"""


def rows_html(rows):
return "".join([f"<div class='card'><h2>{k}</h2><div><strong>{v}</strong></div></div>" for k, v in rows])


cfg_block = ""
if summary:
cfg_block = (
f"<p><strong>Symbols:</strong> {', '.join(summary.get('symbols', []))} &nbsp;|&nbsp; "
f"<strong>Bar:</strong> {summary.get('bar_interval')} &nbsp;|&nbsp; "
f"<strong>Session:</strong> {summary.get('session')}<br/>"
f"<strong>Slippage:</strong> {summary.get('slippage_bp')} bps &nbsp;|&nbsp; "
f"<strong>Commission:</strong> ${summary.get('commission_per_contract')}</p>"
)


trades_html = trades.head(50).to_html(index=False) if not trades.empty else "<em>No trades.</em>"


html = f"""
<!doctype html>
<html><head><meta charset='utf-8'><title>{title}</title>{css}</head>
<body>
<h1>{title}</h1>
<div>{cfg_block}</div>
<div class='grid'>
{rows_html(metrics_rows)}
</div>
<h2>Equity Curve</h2>
{f"<img src='data:image/png;base64,{eq_img}'/>" if eq_img else "<em>No equity data.</em>"}
<h2>Drawdown</h2>
{f"<img src='data:image/png;base64,{dd_img}'/>" if dd_img else "<em>No drawdown data.</em>"}
<h2>R-Multiple Distribution</h2>
{f"<img src='data:image/png;base64,{r_img}'/>" if r_img else "<em>No trades.</em>"}
<h2>Trades (first 50)</h2>
{trades_html}
<p><a href='trades.csv'>Download full trades.csv</a></p>
<div class='footer'>Assumptions: slippage bps and per-contract commissions as configured. Generated by Olivia.</div>
</body></html>
"""


out = run_dir / 'report.html'
out.write_text(html, encoding='utf-8')
return out
