from __future__ import annotations
from typing import Protocol, Iterable, Dict, Any


class Broker(Protocol):
def submit_order(self, symbol: str, side: str, qty: int, type: str = "MKT") -> str: ...
def cancel(self, order_id: str) -> None: ...
def positions(self) -> Iterable[Dict[str, Any]]: ...
def account(self) -> Dict[str, Any]: ...
